trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(06bf1072-4b4a-4678-b9fd-c446ea8d3911)'
    appType: 'webApp'
    WebAppName: 'prog-11'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'
